import AmazonPay                       from './front/CFW/Compatibility/Gateways/AmazonPay';
import Braintree                       from './front/CFW/Compatibility/Gateways/Braintree';
import KlarnaCheckout                  from './front/CFW/Compatibility/Gateways/KlarnaCheckout';
import KlarnaPayments                  from './front/CFW/Compatibility/Gateways/KlarnaPayments';
import PayPalForWooCommerce            from './front/CFW/Compatibility/Gateways/PayPalForWooCommerce';
import PayPalPlusCw                    from './front/CFW/Compatibility/Gateways/PayPalPlusCw';
import Square                          from './front/CFW/Compatibility/Gateways/Square';
import Stripe                          from './front/CFW/Compatibility/Gateways/Stripe';
import WooCommercePensoPay             from './front/CFW/Compatibility/Gateways/WooCommercePensoPay';
import WooSquarePro                    from './front/CFW/Compatibility/Gateways/WooSquarePro';
import CO2OK                           from './front/CFW/Compatibility/Plugins/CO2OK';
import EUVatNumber                     from './front/CFW/Compatibility/Plugins/EUVatNumber';
import MondialRelay                    from './front/CFW/Compatibility/Plugins/MondialRelay';
import MyShipper                       from './front/CFW/Compatibility/Plugins/MyShipper';
import NIFPortugal                     from './front/CFW/Compatibility/Plugins/NIFPortugal';
import NLPostcodeChecker               from './front/CFW/Compatibility/Plugins/NLPostcodeChecker';
import OrderDeliveryDate               from './front/CFW/Compatibility/Plugins/OrderDeliveryDate';
import PortugalVaspKios                from './front/CFW/Compatibility/Plugins/PortugalVaspKios';
import PostNL                          from './front/CFW/Compatibility/Plugins/PostNL';
import SendCloud                       from './front/CFW/Compatibility/Plugins/SendCloud';
import ShipMondo                       from './front/CFW/Compatibility/Plugins/ShipMondo';
import WCPont                          from './front/CFW/Compatibility/Plugins/WCPont';
import WooCommerceAddressValidation    from './front/CFW/Compatibility/Plugins/WooCommerceAddressValidation';
import WooCommerceGermanized           from './front/CFW/Compatibility/Plugins/WooCommerceGermanized';
import WooCommerceGiftCards            from './front/CFW/Compatibility/Plugins/WooCommerceGiftCards';
import WooFunnelsOrderBumps            from './front/CFW/Compatibility/Plugins/WooFunnelsOrderBumps';

// eslint-disable-next-line import/prefer-default-export
export const cfwCompatibilityClasses: any = {};

cfwCompatibilityClasses.AmazonPay = AmazonPay;
cfwCompatibilityClasses.Braintree = Braintree;
cfwCompatibilityClasses.CO2OK = CO2OK;
cfwCompatibilityClasses.EUVatNumber = EUVatNumber;
cfwCompatibilityClasses.KlarnaCheckout = KlarnaCheckout;
cfwCompatibilityClasses.KlarnaPayments = KlarnaPayments;
cfwCompatibilityClasses.MondialRelay = MondialRelay;
cfwCompatibilityClasses.NIFPortugal = NIFPortugal;
cfwCompatibilityClasses.NLPostcodeChecker = NLPostcodeChecker;
cfwCompatibilityClasses.OrderDeliveryDate = OrderDeliveryDate;
cfwCompatibilityClasses.PayPalForWooCommerce = PayPalForWooCommerce;
cfwCompatibilityClasses.PayPalPlusCw = PayPalPlusCw;
cfwCompatibilityClasses.PortugalVaspKios = PortugalVaspKios;
cfwCompatibilityClasses.PostNL = PostNL;
cfwCompatibilityClasses.SendCloud = SendCloud;
cfwCompatibilityClasses.ShipMondo = ShipMondo;
cfwCompatibilityClasses.Square = Square;
cfwCompatibilityClasses.Stripe = Stripe;
cfwCompatibilityClasses.WCPont = WCPont;
cfwCompatibilityClasses.WooCommerceAddressValidation = WooCommerceAddressValidation;
cfwCompatibilityClasses.WooCommerceGermanized = WooCommerceGermanized;
cfwCompatibilityClasses.WooCommerceGiftCards = WooCommerceGiftCards;
cfwCompatibilityClasses.WooFunnelsOrderBumps = WooFunnelsOrderBumps;
cfwCompatibilityClasses.WooSquarePro = WooSquarePro;
cfwCompatibilityClasses.WooCommercePensoPay = WooCommercePensoPay;
cfwCompatibilityClasses.MyShipper = MyShipper;
